services:
  # BASE DE DATOS MONGODB LOCAL
  db:
    image: mongo:latest
    container_name: tfg_mongodb
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - tfg_network

  # BACKEND FASTAPI
  backend:
    build:
      context: ./backend
    container_name: tfg_backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    networks:
      - tfg_network

  # FRONTEND NEXT.JS
  frontend:
    build:
      context: ./frontend
    container_name: tfg_frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_BACKEND_URL=http://localhost:8000
    depends_on:
      - backend
    networks:
      - tfg_network

volumes: 
  mongo_data:
networks:
  tfg_network:
